### ISSUE TITLE
[question] Should this repo be moved to random-access-storage organisation?

### ISSUE THREAD

**Issue by e-e-e** [random-access-storage/random-access-memory#6]
Hey @mafintosh, I just noticed that this module is not under the org random-access-storage, is there a reason for this? If not, should we move it over there so its discoverable with the rest of the compliant libs?
Its been great to see all the ras modules coalesce. Whoever instigated it, it was a good idea.

**Comment by mafintosh** [comment]
Ya I'm moving it
